[package]
name = "volatile"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT OR Apache-2.0"
keywords = ["volatile"]
documentation = "https://docs.rs/volatile"
repository = "https://github.com/phil-opp/volatile"

[dependencies]
